import Button from "react-bootstrap/Button";
import Container from "react-bootstrap/Container";
import Form from "react-bootstrap/Form";

const TermsAndConditions = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-2xl font-bold mb-4">Terms & Conditions</h1>

      <p className="mb-4">
        This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>

      <p className="mb-4">
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, which require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name <strong>Oneindiaoff.shop</strong> ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").
      </p>

      <p className="mb-4">
        The Platform is owned by {window.location.hostname}, managed by <strong>RATHOD RAVIBHAI PRAVINBHAI</strong>, with its address at <strong>BHATHIJI FALIYU, BHIMTALAV, ANAND, GUJARAT - 388620</strong> (hereinafter referred to as "Platform Owner", "we", "us", "our"). Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform, including the applicable policies which are incorporated herein by way of reference. By mere use of the Platform, You shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute Your binding obligations with the Platform Owner.
      </p>

      <h2 className="text-xl font-semibold mb-2">Modifications to Terms</h2>
      <p className="mb-4">
        These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
      </p>

      <h2 className="text-xl font-semibold mb-2">User Responsibilities</h2>
      <ul className="list-disc list-inside mb-4">
        <li>
          To access and use the Services, you agree to provide true, accurate, and complete information during and after registration. You are responsible for all acts done through the use of your registered account on the Platform.
        </li>
        <li>
          You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, Indian, or local laws that might apply to you.
        </li>
        <li>
          You agree to pay us the charges associated with availing of the Services.
        </li>
      </ul>

      <h2 className="text-xl font-semibold mb-2">Warranties and Liability</h2>
      <p className="mb-4">
        Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
      </p>
      <p className="mb-4">
        Your use of our Services and the Platform is solely and entirely at your own risk and discretion. We shall not be liable to you in any manner.
      </p>

      <h2 className="text-xl font-semibold mb-2">Intellectual Property</h2>
      <p className="mb-4">
        The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents, including but not limited to the design, layout, look, and graphics.
      </p>

      <h2 className="text-xl font-semibold mb-2">Indemnification</h2>
      <p className="mb-4">
        You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies, and their respective officers, directors, agents, and employees from any claim or demand, including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of these Terms of Use, Privacy Policy, or other Policies, or Your violation of any law, rules, or regulations, or the rights (including infringement of intellectual property rights) of a third party.
      </p>

      <h2 className="text-xl font-semibold mb-2">Force Majeure</h2>
      <p className="mb-4">
        Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
      </p>

      <h2 className="text-xl font-semibold mb-2">Governing Law and Jurisdiction</h2>
      <p className="mb-4">
        These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Gujarat.
      </p>

      <h2 className="text-xl font-semibold mb-2">Contact Information</h2>
      <p className="mb-4">
        All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
      </p>
    </div>
                <div className="text-center">
                    <h3 style={{fontSize: '18px', fontWeight: 700, color: '#727272', textAlign: 'center'}}>Get Our
                        Newsletter</h3>
                    <div className="Footer__Content Rte">
                        Subscribe to receive update, access to exclusive deals, and more.
                    </div>
                    <Form method="post" action="/contact#footer-newsletter" id="footer-newsletter"
                          accept-charset="UTF-8" className="my-3">
                        <input type="hidden" name="form_type" value="customer"/>
                        <input type="hidden" name="utf8" value="✓"/>
                        <input type="hidden" name="contact[tags]" value="newsletter"/>
                        <Form.Control size="lg" type="email" placeholder="Enter email"/>
                        <Button type="button" variant="dark" className="mt-3" style={{
                            background: "var(--them-color)",
                            borderColor: "var(--them-color)",
                        }}>Subscribe</Button>
                    </Form>
                </div>
            </div>
        </Container>
    );
}

export default Termsofservice;
